WITH CAN_RENTAL AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING(CAR_ID)
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    ) AND CAR_TYPE IN ('세단', 'SUV') 
)

SELECT CAR_ID, CAR_TYPE, 
        FLOOR(30 * DAILY_FEE * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM CAN_RENTAL JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING(CAR_TYPE)
WHERE DURATION_TYPE = '30일 이상'
        AND 500000 <= FLOOR(30 * DAILY_FEE * (100 - DISCOUNT_RATE) / 100)
        AND FLOOR(30 * DAILY_FEE * (100 - DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC