WITH JULY_SUM AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JSUM
    FROM JULY
    GROUP BY FLAVOR
), FIRST_HALF_SUM AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS HSUM
    FROM FIRST_HALF
    GROUP BY FLAVOR
)

SELECT FLAVOR
FROM JULY_SUM FULL JOIN FIRST_HALF_SUM USING(FLAVOR)
ORDER BY JSUM + HSUM DESC
LIMIT 3